name: AI Change Request
description: Request a website/content change in plain language.
title: "[AI Request] "
labels:
  - ai-change-request
body:
  - type: markdown
    attributes:
      value: |
        Explain the change in plain language. The automation will draft a PR from this issue.
        One issue = one change request. No sub-issues.

  - type: textarea
    id: change_request
    attributes:
      label: What change do you want?
      description: Tell us what to update and what the new content/behavior should be.
      placeholder: |
        Example:
        Update the homepage hero headline from "A modern LMS for learning" to "A modern LMS for teaching and learning."
        Also update the CTA button text from "Try Sakai LMS Free" to "Get a Sakai LMS Demo."
        Page: /
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: Reference material
      description: Links, source content, screenshots, style notes.
      placeholder: https://www.sakailms.org/... plus any source copy text.
